owner: petebachant
name: calkit-project-1
title: My first Calkit project
description:
git_repo_url: https://github.com/petebachant/calkit-project-1
datasets:
  - path: data/raw/data.csv
    title: Raw data
    description: This is raw voltage data.
    stage: collect-data
figures:
  - path: figures/voltage-time-series.png
    title: Raw voltage time series
    description: A plot of the raw voltage time series.
    stage: plot-voltage
publications:
  - path: paper/paper.pdf
    title: The paper
    description: This is the paper.
    stage: build-paper
  - path: paper-2/main.pdf
    title: Paper 2
    description:
    kind:
    stage: build-paper-2
  - path: pubs/paper-2/main.pdf
    title: Paper 2
    description:
    kind:
    stage: build-pubs-paper-2
environments:
  py:
    path: environment.yml
    kind: conda
    description: A Python environment
  tex:
    kind: docker
    image: texlive/texlive:latest-full
    wdir: /work
    description: TeX Live via Docker.
derived_from:
  project: calkit/example-basic
  git_repo_url: https://github.com/calkit/example-basic
  git_rev: e28aea580724deb20719f24d1ff401840bd416aa
pipeline:
  stages:
    make-thing:
      kind: shell-command
      environment: _system
      command: echo "Making a thing" > paper-2/thing.txt
      outputs:
        - paper-2/thing.txt
    build-paper-2:
      name:
      kind: latex
      environment: tex
      wdir:
      inputs: []
      outputs: []
      always_run: false
      iterate_over:
      description:
      target_path: paper-2/main.tex
      latexmkrc_path:
      verbose: false
      force: false
      synctex: true
    build-pubs-paper-2:
      name:
      kind: latex
      environment: tex
      wdir:
      inputs: []
      outputs: []
      always_run: false
      iterate_over:
      description:
      target_path: pubs/paper-2/main.tex
      latexmkrc_path:
      verbose: false
      force: false
      synctex: true

overleaf_sync:
  paper-2:
    url: https://www.overleaf.com/project/54b68eff0ee71ad2767b704a
  pubs/paper-2:
    url: https://www.overleaf.com/project/54b68eff0ee71ad2767b704a
